FROM golang:1.8
MAINTAINER Guangzheng Zhang <zhang.elinks@gmail.com>
WORKDIR /go
# install golint
RUN mkdir -p /go/src/golang.org/x/ && \
	git clone https://github.com/golang/tools/ -b release-branch.go1.8 /go/src/golang.org/x/tools && \
	go get github.com/golang/lint/golint
ENV PKG=github.com/bbklab/swan-ng SRC_DIR=/src PRODUCT_DIR=/product  IN_CONTAINER=yes
CMD ["/src/tools/build.sh"]
